三界斗命令: gcb
物资名称: §a斗币§r§f
消息前缀: §b三界斗 §a>>> §7
UI标题: §e三界斗
上次获胜势力: §b神界§r
最终开盘: 随机
斗币变量: '{dcoin}'
战利品返还倍率: 2.7
三界斗次数: 1
最小增援: 1000
最大增援: 10000
默认斗币数量: 100
保留战事日志数量: 300
保留玩家增援记录: 50
战局时长: 600
战局倒计时记录: 600
规则介绍: |-
  每次战事为十分钟,
  可以选择支援自己喜欢的某个势力进行支援,
  如果支援的势力在本局中取得最终胜利，
  支援获胜方可获得2.7倍支援物资
  每个势力的获胜几率相同
  严禁利用游戏进行外围
  (什么是外围?外围指利用随机结果进行现实中的金钱赌博)
势力列表:
  - §b神界§r
  - §e佛界§r
  - §c魔界§r
战局:
  - '{win} §r§f趁夜劫粮, {lose} §r§f士气大减'
  - '{win} §r§f大受鼓舞,强攻 {lose} §r§f大营'
  - '{win} §r§f使用火计, {lose} §r§f中计损兵'
  - '{win} §r§f武将单挑,直取 {lose} §r§f武将首级'
  - '{win} §r§f山路埋伏, {lose} §r§f中伏惨败'
  - '{win} §r§f全军冲锋, {lose} §r§f战线后退'
  - '{win} §r§f增兵前线, {lose} §r§f士气低落'
  - '{win} §r§f假传军令, {lose} §r§f中计内斗'
  - '{win} §r§f援军到达, {lose} §r§f受夹击大败'
  - '{win} §r§f迂回攻击, {lose} §r§f侧翼受损'
  - '{win} §r§f新得名将, {lose} §r§f士气低落'
  - '{win} §r§f得奇才军事, {lose} §r§f人心浮动'
  - '{win} §r§f奉旨讨逆, {lose} §r§f人心不稳'
  - '{win} §r§f偷袭后方, {lose} §r§f士气大落'
  - '{win} §r§f深夜偷营, {lose} §r§f损失惨重'
  - '{win} §r§f长驱直入, {lose} §r§f主将受伤'
  - '{win} §r§f使用诈降计, {lose} §r§f中计受损'
  - '{win} §r§f调动船队突袭, {lose} §r§f水军大败'
  - '{win} §r§f猛将直取 {lose} §r§f主将,士气大振'
  - '{win} §r§f阵法精奇, {lose} §r§f无以应对'
  - '{win} §r§f无懈可击, {lose} §r§f无可奈何'
  - '{win} §r§f指挥若定, {lose} §r§f无功而返'
  - '{win} §r§f三军齐动, {lose} §r§f望风而逃'
  - '{win} §r§f诱敌深入, {lose} §r§f中伏大败'
  - '{win} §r§f火箭齐射, 火烧 {lose} §r§f大营'
上次获胜玩家: []
势力增援: []
增援玩家列表:
  - §b神界§r: []
  - §e佛界§r: []
  - §c魔界§r: []
战事日志: []
